# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo/docs

    steps:
      - checkout

      - run:
          name: start application
          command: | 
          python3 -m http.server 8000
          sleep 5
          background: true

      - run:
          name: run tests
          command: |
            curl http://0.0.0.0:8000/